- hosts: manager
  tasks:
     - name: Configuring Manager Node
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode manager -replication_factor 2 -search_factor 2 -secret 123456789 -cluster_label Indexer_Cluster -auth admin:Tata@123
             
     - name: pause
       pause:
          minutes: 1
          
     - name: splunk restart for Configuring Manager Node
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk restart
           
- hosts: peer
  tasks:
     - name: Configuring Peer Nodes
       become: yes
       become_user: root
       command:
             cmd: /opt/splunk/bin/splunk edit cluster-config -mode peer -manager_uri https://43.204.150.131:8089 -replication_port 8085 -secret 123456789 -auth admin:Tata@123
             
     - name: pause
       pause:
           minutes: 1
          
     - name: splunk restart for Configuring Manager Node
       become: yes
       become_user: root
       command:
            cmd: /opt/splunk/bin/splunk restart
 
             
