- hosts: deployer
  tasks:
    - name: enable the clustering in deployer
      become: yes
      become_user: root
      copy: 
         dest: /opt/splunk/etc/system/local/server.conf
         content: |
            [shclustering]
            shcluster_label = shcluster1
            pass4SymmKey = 123456789
    - name: restart
      become: yes
      become_user: root
      command:
            cmd: /opt/splunk/bin/splunk restart

- name: shc1 
  hosts: shcluster1
  user: root
  become: yes

  tasks:
    - name: restart splunkd
      command: /opt/splunk/bin/splunk restart
      
    - name: configure search peer 
      command: /opt/splunk/bin/splunk init shcluster-config -auth admin:Tata@123 -mgmt_uri https://13.126.211.205:8089 -replication_port 8085 -replication_factor 2 -conf_deploy_fetch_url https://43.204.231.221:8089 -secret 123456789 -shcluster_label shcluster1

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart

- name: shc 2 
  hosts: shcluster2
  user: root
  become: yes

  tasks:
    - name: restart splunk
      command: /opt/splunk/bin/splunk restart
    
    - name: configure search peer 
      command: /opt/splunk/bin/splunk init shcluster-config -auth admin:Tata@123 -mgmt_uri https://3.110.189.218:8089 -replication_port 8085 -replication_factor 2 -conf_deploy_fetch_url https://43.204.231.221:8089 -secret 123456789 -shcluster_label shcluster1

    - name: restart splunk
      command: /opt/splunk/bin/splunk restart
    

- name: shc 1 captain
  hosts: shcluster1
  user: root
  become: yes

  tasks:
    - name: Making cluster captain
      command: /opt/splunk/bin/splunk bootstrap shcluster-captain -servers_list "https://3.110.189.218:8089,https://13.126.211.205:8089" -auth admin:Tata@123

